name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [1.0.0, latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}
    
    - name: Install dependencies
      run: bun install
    
    - name: Run TypeScript type check
      run: bun run typecheck
    
    - name: Run tests
      run: bun test
    
    - name: Build project
      run: bun run build
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.bun-version == 'latest'
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false